source :rubygems

# required to run travis
gem 'travis'

# Travis will append your library's Gemfile here if it exists. You can also
# list any gems manually here.
gem 'activerecord'
gem 'activesupport'
gem 'sqlite3-ruby'
gem 'mocha'