source :rubygems

# gems required to run travis
gem 'sinatra'
gem 'bob'
gem 'data_mapper'
gem 'data_objects'
gem 'do_postgres'

# Travis will append your library's Gemfile here if it exists. You can also
# list any gems manually here.
gem 'activerecord'
gem 'activesupport'
gem 'sqlite3-ruby'
gem 'mocha'